{
    "name": "Noel's Pharmacy Website & eCommerce",
    "summary": "Premium Odoo storefront and secure online prescription intake for Noel's Pharmacy",
    "version": "19.0.1.0.3",
    "category": "Website/eCommerce",
    "author": "SPXCORP Limited",
    "website": "https://spxcorp.net",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "mail",
        "portal",
        "website",
        "website_sale",
    ],
    "data": [
        "security/noels_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/mail_templates.xml",
        "data/website_defaults.xml",
        "views/prescription_request_views.xml",
        "views/contact_request_views.xml",
        "views/brand_views.xml",
        "views/settings_views.xml",
        "views/backend_menus.xml",
        "views/website_layout.xml",
        "views/website_home.xml",
        "views/website_pages.xml",
        "views/website_prescription.xml",
        "views/portal_templates.xml",
        "views/website_sale_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "noels_pharmacy_website/static/src/css/noels.css",
            "noels_pharmacy_website/static/src/js/noels.js",
        ],
    },
    "images": ["static/description/banner.png"],
    "application": True,
    "installable": True,
}
